version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-backend
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    container_name: redis-backend
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory ${REDIS_MAX_MEMORY:-256mb}
      --maxmemory-policy allkeys-lru
      ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - dev-network

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb-backend
    ports:
      - "${SURREALDB_PORT:-8000}:8000"
    environment:
      - SURREAL_USER=${SURREALDB_USERNAME:-root}
      - SURREAL_PASS=${SURREALDB_PASSWORD:-root}
    volumes:
      - surrealdb_data:/data
    command: >
      start
      --log trace
      --user ${SURREALDB_USERNAME:-root}
      --pass ${SURREALDB_PASSWORD:-root}
      --bind 0.0.0.0:8000
      file:/data/database.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dev-network

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local
  surrealdb_data:
    driver: local

networks:
  dev-network:
    driver: bridge