services:
  minio:
    image: minio/minio:latest
    container_name: minio-backend
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-admin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-password123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    container_name: redis-backend
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory ${REDIS_MAX_MEMORY:-256mb}
      --maxmemory-policy allkeys-lru
      ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - dev-network

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb-backend
    ports:
      - "${SURREALDB_PORT:-8000}:8000"
    environment:
      - SURREAL_USER=${SURREALDB_USERNAME:-root}
      - SURREAL_PASS=${SURREALDB_PASSWORD:-root}
      - SURREAL_LOG=info
      - SURREAL_BIND=0.0.0.0:8000
    command: ["start", "--user", "${SURREALDB_USERNAME:-root}", "--pass", "${SURREALDB_PASSWORD:-root}", "memory"]
    healthcheck:
      test: ["CMD", "/surreal", "is-ready", "--endpoint", "http://localhost:8000"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - dev-network

  surrealdb-mcp:
    image: surrealdb/surrealmcp:latest
    container_name: surrealdb-mcp-server
    ports:
      - "${SURREALDB_MCP_PORT:-3004}:3004"
    environment:
      - SURREALDB_URL=http://surrealdb:8000/rpc
      - SURREALDB_NS=${SURREALDB_NAMESPACE:-test}
      - SURREALDB_DB=${SURREALDB_DATABASE:-test}
      - SURREALDB_USER=${SURREALDB_USERNAME:-root}
      - SURREALDB_PASS=${SURREALDB_PASSWORD:-root}
      - MCP_TRANSPORT=http
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3004
    command: ["start", "--bind-address", "0.0.0.0:3004"]
    depends_on:
      surrealdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep surrealmcp > /dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - dev-network

volumes:
  minio_data:
    driver: local
  redis_data:
    driver: local
  surrealdb_data:
    driver: local

networks:
  dev-network:
    driver: bridge